[package]
name = "bddap-aoc-macros"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.38"

